### ISSUE TITLE
CBotTasks.as: Division by zero error in L2416, function calculateUtility

### ISSUE THREAD

**Issue by Outerbeast** [rcbotCheeseh/RCBotSven5#11]
https://github.com/rcbotCheeseh/RCBotSven5/blob/master/CBotTasks.as#L2416
It seems to happen when a bot dies

`Not allowed: in section 'b:/games/steam/steamapps/common/sven co-op/svencoop_addon/scripts/plugins/botmanager/cbottasks.as', at (2416, 9): Function calculateUtility:
Message: Divide by zero`

As long as the bot is dead, the logs will be flooded with this error message and the game will eventually crash

**Comment by rcbotCheeseh** [comment]
fix for now in commit a63ce94cafff28af6538cd378d1454b21cc0c380
